name:                syncry
version:             0.1.0.0
github:              "buzden/syncry"
license:             BSD3
author:              "Denis Buzdalov"
maintainer:          "buzdalov@ispras.ru"
copyright:           "2019 Denis Buzdalov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/buzden/syncry#readme>

dependencies:
- base >= 4.7 && < 5
- syntax >= 1
- syntax-attoparsec >= 1
- syntax-printer >= 1

library:
  source-dirs: src

executables:
  syncry-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - syncry

tests:
  syncry-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - syncry
