resolver: lts-13.30

packages:
- .
- third-party/semi-iso

extra-deps:
- syntax-1.0.0.0@sha256:3959bcb0cea2f2e1d1bf643306962551f6888b0db888beb632477c7929e6966d
- syntax-attoparsec-1.0.0.0@sha256:06027060943c21a6b896dab4082b311b70499f04fbcb168587628e9d256d066a
- syntax-printer-1.0.0.0@sha256:54aa9d28dc20b5d84a155d747746b57d7ad895107bb6d03e0bebcbd2547c43fa

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor

allow-newer: true
# To remove `allow-newer` as soon as `syntax-printer` gets nice base-4.12 dependency.
